<template>
<div>
  <section class="accordion-section clearfix mt-3" aria-label="Question Accordions">
    <div class="container">
      <h1>Frequently Asked Questions</h1>
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
          <div class="panel-heading p-3 mb-3" role="tab" id="heading0">
            <h3 class="panel-title">
              <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0">
                How to use the Cyber Resilience Quantification Tool?
              </a>
            </h3>
          </div>
          <div id="collapse0" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading0">
            <div class="panel-body px-3 mb-4 text-justify">
              <p>
                The CRQT has two forms of input approaches: a data-driven and model-driven approach. 
                Based on the input approach, the CRQT will produce a set of cyber-resilience metrics 
                for your inputted method approach. (Ex. a model-driven network will produce graph-based metrics)
              </p>
              <ul>
                <li class="pb-2">
                  <strong>Data-Driven:</strong> When you have the ability to probe a network or have the network 
                  configurations already, you can input that data into 
                  <a target="_blank" href="http://people.cs.ksu.edu/~xou/mulval/">
                    MulVAL
                  </a>
                  to parse through the network data and format the network topology into an acceptable format
                  for our tool (2 CSV files). You can input your data-driven network topology 
                  <router-link to="/network-topology/data-driven">here.</router-link>
                </li>
                <li>
                  <strong>Model-Driven:</strong> When you cannot probe a network, have the sufficent network data, 
                  or if you would like to develop you own unique network topology, you can build your own 
                  network infastructure using network hardware/software components your organization has added as
                  possible selections into the tool. You can build your own model-driven network topology 
                  <router-link to="/network-topology/model-driven">here.</router-link>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading p-3 mb-3" role="tab" id="heading1">
          <h3 class="panel-title">
            <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" aria-controls="collapse1">
              How are cyber networks evaluated?
            </a>
          </h3>
          </div>
          <div id="collapse1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading1">
            <div class="panel-body px-3 mb-4">
              <p class="text-justify">
                Cyber networks are evaluated based on your input methodology:
                <ul>
                  <li class="pb-2">
                    <strong>Data-Driven:</strong> An inputted network topology is inputted as a Logical Attack Graph (LAG)
                    and a weighted LAG is generated by adding node weights to primitive nodes in the network. The node 
                    weights are the CVSS scores (base, exploitability, and impact) associated with primitive node. A breakdown
                    of how CVSS scores are calculated and what they represent can be found in 
                    <a href="http://localhost:8080/references/51198.pdf">
                      A Complete Guide to the Common Vulnerability Scoring System Version 2.0.
                    </a>
                    Based on the calculated weighted CVSS scores for each node, that are how specific metrics and recommendations 
                    are calculated.
                  </li>
                  <li>
                    <strong>Model-Driven:</strong> An inputted network topology is inputted as a vulnerabiity graph and 
                    a weighted vulnerability graph is generated by adding edge weights between selected network components. 
                    The edge weights represent the CVSS scores associated with the target node between two network components. A breakdown
                    of how CVSS scores are calculated and what they represent can be found in 
                    <a href="http://localhost:8080/references/51198.pdf">
                      A Complete Guide to the Common Vulnerability Scoring System Version 2.0.
                    </a>
                    Based on the calculated weighted CVSS scores for each edge, that are how specific metrics are calculated. 
                  </li>
                </ul>
              </p>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
          <h3 class="panel-title">
            <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="true" aria-controls="collapse2">
              How are recommendations produced?
            </a>
          </h3>
          </div>
          <div id="collapse2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
            <div class="panel-body px-3 mb-4">
              <p class="text-justify">
                Network recommendations are calculated based on your input methodology:
                <ul>
                  <li class="pb-2">
                    <strong>Data-Driven:</strong> The recommendations for a data-driven network ranks nodes derived fact nodes 
                    in a logical attack graph by their derived CVSS base score and vulnerabilities at primitive fact nodes 
                    based on their CVSS base score retrieved from <a href="https://nvd.nist.gov/vuln/data-feeds">NIST's NVD Data feeds</a>.
                    The recommendations do not provide the technical details on how to specifically fix the issue but rather informs 
                    users where their extra security efforts or funding should be placed. The user should address each node in 
                    the order that they are ranked and to see the noticeable improvement in their network reinput their
                     new network topology with the fixed nodes. 
                  </li>
                  <li>
                    <strong>Model-Driven:</strong> The recommendations for a model-driven network ranks nodes based by device criticality 
                    which is found by applying the TOPSIS method with the associated weights provided to us by Shetty and Haque 
                    <a href="http://localhost:8080/references/Resilience Week 2019-000361.pdf" target="_blank">[5]</a>. 
                    From the ranked nodes using the TOPSIS score, users are recommended to fix each node following the order that they are
                    ranked. From there, a user can then reinput their new network topology with their fixed nodes to see how their 
                    network has improved or if there any additional nodes that they need further attention.
                  </li>
                </ul>
              </p>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading p-3 mb-3" role="tab" id="heading3">
          <h3 class="panel-title">
            <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse3" aria-expanded="true" aria-controls="collapse3">
              Are there any computer specification requirements associated with this tool?
            </a>
          </h3>
          </div>
          <div id="collapse3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
            <div class="panel-body px-3 mb-4">
              <p class="text-justify">
                Based on our computational analyis running the tool, we have indentified if you are inputting large networks into the system 
                (over 1000+ nodes and 1000+ connections) that computer memory space will be important for calculating the necessary metrics. 
                If however, the CRQT is deployed server side this will not be a requirement for a client machine but will be a requirement of the sponsoring
                organization to configure the deployment enviornment correctly to sufficiently handle memory allocation requirements. 
              </p>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading p-3 mb-3" role="tab" id="heading4">
          <h3 class="panel-title">
            <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse4" aria-expanded="true" aria-controls="collapse4">
              Who to contact if I have an issue using the tool?
            </a>
          </h3>
          </div>
          <div id="collapse4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading4">
            <div class="panel-body px-3 mb-4">
              <p class="text-justify">
                If you have any issues with using the tool or have found any issues, please email Dr. Sachin Shetty (sshetty@odu.edu),
                Md. Ariful Haque (mhaqu001@odu.edu), and Kyle Tanyag (ktany001@odu.edu).
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
</template>

<script>

export default {
  name: 'FAQ' 
}

</script>
<style>
.accordion-section .panel-default > .panel-heading {
  border: 0;
  background: #f4f4f4;
  padding: 0;
}
.accordion-section .panel-default .panel-title a {
  display: block;
  font-size: 1.5rem;
}
.accordion-section .panel-default .panel-title a:after {
  font-family: 'FontAwesome';
  font-style: normal;
  font-size: 3rem;
  content: "\f106";
  color: #1f7de2;
  float: right;
  margin-top: -12px;
}
.accordion-section .panel-default .panel-title a.collapsed:after {
  content: "\f107";
}
.accordion-section .panel-default .panel-body {
  font-size: 1.2rem;
}
</style>